### ISSUE TITLE
Provide detailed forecast in sensor attribute

### ISSUE THREAD

**Issue by rany2** [rany2/ha-open-meteo-solar-forecast#1]
Similar to Solcast integration

**Comment by gieljnssns** [comment]
Are you going to use attributes or a service response?

**Comment by rany2** [comment]
Service response makes more sense but the user request is for it to be in entity. If it makes no difference in ApexCharts, I would prefer service response. I'll need to ask as I don't use ApexCharts.

**Comment by rany2** [comment]
For how to make it work with ApexCharts, see https://community.home-assistant.io/t/open-meteo-solar-forecast/733073/118?u=rany

**Comment by andreas-bulling** [comment]
Can you/someone else put the actual example here for how to generate an apexchart forecast plot similar to the HA Dashboard?

**Comment by rany2** [comment]
Doing this in sensor attributes is much easier and most users are going to make a new sensor that calls a service if I went with the service approach :)

**Comment by rany2** [comment]
> Can you/someone else put the actual example here for how to generate an apexchart forecast plot similar to the HA Dashboard?

I'm sorry, I don't use ApexChart. I recommend you ask in the forum thread :)
