### ISSUE TITLE
Impossible Forecast

### ISSUE THREAD

**Issue by Statusbit** [rany2/ha-open-meteo-solar-forecast#27]
![Screenshot_20240907-092453](https://github.com/user-attachments/assets/d21b247d-a282-4e00-9fcb-ba2a0cbeef52)
![Screenshot_20240907-092419](https://github.com/user-attachments/assets/b55fd377-b741-43f9-9970-f92d9d6118a7)
The peak power cannot be, can anyone explain this?

**Comment by rany2** [comment]
Thanks for the report, I'm looking into it. Can you let me know if the your power (not energy) forecast sensors are also exhibiting this behavior?

**Comment by Statusbit** [comment]
![Screenshot_20240907-101536](https://github.com/user-attachments/assets/b6cfa278-15f8-4137-a80b-214de993abab)
I had activated 2 predictions. Sorry for the confusion.
