### ISSUE TITLE
Forecast value doesnt match

### ISSUE THREAD

**Issue by bennyrbg** [rany2/ha-open-meteo-solar-forecast#29]
Hi all together,

i configured the rep and set an offset for the "next 12h" sensor from the meteo forecast with my current power sensor and it works great:
<img width="295" alt="image" src="https://github.com/user-attachments/assets/75376a19-f2c8-4b4d-826b-fa63d84ef0cb">

It looks like the curve is allright, but the values are way to high.
Also the daily output is calculated wrong and is far away from reality. 

Any idea what I am doing wrong?
<img width="341" alt="{18D1DB67-3BD3-424E-B81E-9BD5954A117C}" src="https://github.com/user-attachments/assets/3a2c52bc-41a2-4069-b18c-64a78f7945bd">

Thanks in advance

**Comment by rany2** [comment]
The panel watt is the power from the panels at STC not the actual maximum they're capable of.

If this isn't the issue and you did set that correctly, then look into reducing the DC efficiency factor.

**Comment by bennyrbg** [comment]
Whats the difference between STC (Standard Test Conditions) and the maximum they are capable of? I thought thats the same?

Looks like I need to reduce from 0,95 to around 0,3 to gain nearly accurate values. 
I will try and observe the coming days - but I still dont get the problem (am i the only one?)

**Comment by rany2** [comment]
> Whats the difference between STC (Standard Test Conditions) and the maximum they are capable of? I thought thats the same?

It's not the same. Your panels could exceed the power that they are rated for.

> Looks like I need to reduce from 0,95 to around 0,3 to gain nearly accurate values. I will try and observe the coming days - but I still dont get the problem (am i the only one?)

Some people have stated that changing the DC efficiency does help them. I might rename the option to something more generic like multiplier instead.

-------------------------------------

Are you in an area that experiences a lot of cloud cover?

**Comment by bennyrbg** [comment]
> Are you in an area that experiences a lot of cloud cover? Edit: is there currently a lot of cloud cover where you're located?

Absolutely yes, today its really cloudy with some breaktroughs of sun.
Last 2 hours were quite sunny, so as you can see, it hits the forecast: 

<img width="371" alt="{4F04EE66-ACB1-4BBA-BEC9-267C03199ED3}" src="https://github.com/user-attachments/assets/bdbace80-778e-4ee9-9d84-54d1f4e48ad1">

**Comment by rany2** [comment]
I can't fix this unfortunately. The data doesn't account for cloud cover very well.
