### ISSUE TITLE
Updates to the integration are not "noticed"/shown by HACS

### ISSUE THREAD

**Issue by andreas-bulling** [rany2/ha-open-meteo-solar-forecast#5]
Updating the repository information doesn't show any new updates. I was stuck on 0.1.2 for a week before I realised that there is 0.1.9 already. Only when I manually "re-downloaded" the integration and restarted HA did it show the latest version.

**Comment by gieljnssns** [comment]
https://community.home-assistant.io/t/open-meteo-solar-forecast/733073/95

**Comment by rany2** [comment]
I think this can be closed, I think the issue is fixed after I switched to GitHub releases.

**Comment by andreas-bulling** [comment]
still doesn't work for me - what do I have to do?

**Comment by rany2** [comment]
@andreas-bulling do note the following: https://hacs.xyz/docs/basic/updates/

Could it be that you didn't give HACS enough time to check for updates?

**Comment by andreas-bulling** [comment]
I restarted HA which should trigger an update according to the docs. Didn't work.

I went into "HACS -> Integrations -> HA Open-Meteo Solar Forecast Integration -> ... -> Update Information". Also didn't work, i.e. didn't show v0.1.10

**Comment by rany2** [comment]
I can't repro, sorry :( 

![image](https://github.com/rany2/ha-open-meteo-solar-forecast/assets/71077389/006a484a-c164-423b-a1e6-432752fd51d9)
