### ISSUE TITLE
Unable to configure on HA pre-2024.4.0b0

### ISSUE THREAD

**Issue by GSV3MiaC** [rany2/ha-open-meteo-solar-forecast#7]
I get the message "Config flow could not be loaded: {"message":"Invalid handler specified"}" when I try to load this integration (running an old version of HA, under docker). Do I need to update HA to make this work or am I doing something else wrong??

**Comment by rany2** [comment]
No idea, but I'm only testing in the latest HA version.

**Comment by GSV3MiaC** [comment]
Further info it says "Logger: homeassistant.config_entries
Source: config_entries.py:2069
First occurred: 9:32:46 PM (1 occurrences)
Last logged: 9:32:46 PM

Error occurred loading flow for integration open_meteo_solar_forecast: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)"

I guess you use that for something and old version of HA does not have it?

I try to avoid HA updates under docker... half my integrations will break every time.

**Comment by rany2** [comment]
Then it's because your HA version is too old

**Comment by rany2** [comment]
https://github.com/home-assistant/core/commit/a0e558c4576cd8228ea8af9d3533438721b22d4f

**Comment by GSV3MiaC** [comment]
Thanks Rany, looks like I need to schedule a day for a major update then, or else hack your Py to use the older HA handler definitions. 

⁣Rgds, Dave Storey​

**Comment by rany2** [comment]
I've kept this issue open because I intend to fix this issue and support both older and newer HA versions but I'll need some time before I could work on it.

**Comment by GSV3MiaC** [comment]
That's great. I am basically using solcast still, so it isn't urgent, I was just looking for alternatives, with fewer restrictions and maybe more customization w.r.t. Horizon and shading. 

⁣Rgds, Dave Storey​

**Comment by GSV3MiaC** [comment]
OK, the config flow no longer errors, but the sensors(and platform) are failing to set up, so I guess something else is inconsistent with older HA release. Logs, sent to Rany.

**Comment by rany2** [comment]
> Logs, sent to Rany.

I haven't received anything, unfortunately
